Repository deemo-o/Zen, pull requests merged in 2023-01, with the labels that each got.

#1 implemented some funni apis
  cogs/fun.py
Labels: Bug, Features

#2 Weather api
  cogs/general.py
Labels: Features, Question

#4 Feature/economy
  .gitignore
  cogs/economy.py
  database_utils/economy_database.py
  database_utils/queries.py
  economy_utils/dboperations.py
Labels: Features, Help

#7 Feature/battleship
  cogs/economy.py
  cogs/games.py
  database_utils/database.db
  database_utils/economy_database.py
  database_utils/economy_queries.py
  database_utils/games_database.py
  database_utils/games_queries.py
  economy_utils/economy_dboperations.py
  games_utils/battleship_dboperations.py
Labels: Features, Help

#8 Feature/yugioh api
  .gitignore
  cogs/yugioh.py
Labels: Features

#14 Feature/moderation
  cogs/fun.py
  cogs/general.py
  cogs/moderation.py
  cogs/music.py
  zen.py
Labels: Features, Help

#19 Feature/typeracer-game
  cogs/games.py
  utils/database_utils/games_database.py
  utils/database_utils/games_queries.py
  utils/games_utils/glicko2.py
  utils/games_utils/paragraph_formatter.py
  utils/games_utils/typeracer_dboperations.py
Labels: Features, Help

#20 Bug/music player
  .gitignore
  cogs/general.py
  cogs/moderation.py
  cogs/music.py
  cogs/system.py
  utils/games_utils/rps_dboperations.py
  utils/music_utils/source.py
  utils/zen_utils/help.py
  zen.py
Labels: Bug, Features, Help, Refactoring
